# Lesson 02 - NumPy 陣列與向量化

1. NumPy 的重點是「一次處理一整組數字」。
2. 這比用 `for` 逐筆計算更簡潔，也通常更快。

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 30)
pd.set_option("display.float_format", "{:,.2f}".format)

DATA_DIR_CANDIDATES = [
    Path("../data/raw"),
    Path("data/raw"),
    Path("/content/Py_dataAna/code/data/raw"),
    Path("/content/code/data/raw"),
]

DATA_DIR = next((path for path in DATA_DIR_CANDIDATES if (path / "orders.csv").exists()), None)
if DATA_DIR is None:
    raise FileNotFoundError(
        "找不到 CSV 資料。請確認 code/data/raw/ 內有 orders.csv 等資料檔，"
        "在 Colab 可先上傳整個專案資料夾或掛載 Google Drive。"
    )

print("Using data folder:", DATA_DIR.resolve())

Using data folder: E:\py_20260620\data\raw


## 建立陣列

In [2]:
prices = np.array([120, 250, 80, 360, 199])
quantities = np.array([1, 2, 4, 1, 3])

line_totals = prices * quantities #相同位置進行計算
line_totals

array([120, 500, 320, 360, 597])

In [3]:
a = prices * 0.8
a

array([ 96. , 200. ,  64. , 288. , 159.2])

In [4]:
b = prices // 5.0 #整數除 的 商
print(b)

[24. 50. 16. 72. 39.]


## 布林條件與篩選

條件判斷會產生 True / False，可以拿來篩資料。

In [5]:
# line_totals -> array([120, 500, 320, 360, 597])
is_large = line_totals >= 300
print(is_large)
print(line_totals[is_large])

print(line_totals[line_totals >= 300])

[False  True  True  True  True]
[500 320 360 597]
[500 320 360 597]


## 用真實資料練習 NumPy

In [8]:
order_items = pd.read_csv(DATA_DIR / "order_items.csv")

quantity = order_items["quantity"].to_numpy()
unit_price = order_items["unit_price"].to_numpy()
#discount_rate = order_items["discount_rate"].to_numpy()#注意欄位名稱須符合變數命名規則
discount_rate = order_items.discount_rate.to_numpy()


line_revenue = quantity * unit_price * (1 - discount_rate)
print("平均明細營收:", line_revenue.mean())
print("最高明細營收:", line_revenue.max())

平均明細營收: 2767.1515885633535
最高明細營收: 14925.0


## 小練習

試著把 `line_revenue >= 500` 改成不同門檻，看看有幾筆高金額明細。

In [ ]:
print(len(line_revenue))#資料數量
print(type(line_revenue))#查詢類型
print(np.mean(line_revenue))#平均值
print(np.max(line_revenue))#最大值
print(np.min(line_revenue))#最小值

39627
<class 'numpy.ndarray'>
2767.1515885633535
14925.0
100.80000000000001


In [14]:
threshold = 500
high_value_count = (line_revenue >= threshold).sum()#統計符合條件的數量
#print(f"明細營收 >= {threshold} 的筆數:", high_value_count)
print(f"明細營收 >= {threshold} 的筆數:{high_value_count}")#格式化輸出

明細營收 >= 500 的筆數:37848
